apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-mysql-pvc
  namespace: fairenough
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-mysql
  namespace: fairenough
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-mysql
  template:
    metadata:
      labels:
        app: gateway-mysql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gateway-mysql-pvc
      containers:
        - name: mysql
          image: mysql:8.0.20
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MYSQL_DATABASE
              value: gateway
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-mysql
  namespace: fairenough
spec:
  selector:
    app: gateway-mysql
  ports:
    - port: 3306
