apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: fairenough
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - name: http
      port: 8080
