kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-fairenough"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 2
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  volume:
    size: "3Gi"
  users:
    gateway: []
    configuration: []
  databases:
    gateway: gateway
    Configuration: configuration
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
