apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: kidscare8playground/gateway
      context: ./gateway
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
